#!/bin/bash

# Make toolchain choose the Java8 JDK instead of earlier versions.
export JAVA8_BUILD=1
source /opt/toolchain/toolchain.sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Extract test jars to the local filesystem, this is expected by some tests
for t in `find . -name "target" -type d`; do
    pushd $t
    mkdir test-classes
    for j in `ls *.jar`; do
        case "$j" in
            *-test-sources.jar | *-tests.jar)
                pushd test-classes
                # Make unzip very quiet (-qq), and default to not overwrite existing files (-n)
                unzip -qq -n ../$j
                popd
            ;;
            *)
            ;;
        esac
    done
    popd
done

junit_out=junit_report.xml

java -Xmx1024m -Dtest.build.data=$DIR/build/test/data -Dorg.schmant.task.junit4.target=$junit_out "$@"

cat $junit_out
