#!/bin/bash

# Make toolchain choose the Java8 JDK instead of earlier versions.
export JAVA8_BUILD=1
source /opt/toolchain/toolchain.sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

mkdir $DIR/test-classes
# Extract test jars to the local filesystem, this is expected by some tests
for t in `find . -name "target" -type d`; do
    pushd $t > /dev/null
    mkdir test-classes
    for j in `ls *.jar`; do
        case "$j" in
            *-test-sources.jar | *-tests.jar)
                JAR=$(readlink -f $j)
                pushd $DIR/test-classes > /dev/null
                # Make unzip very quiet (-qq), and default to not overwrite existing files (-n)
                unzip -qq -n $JAR
                popd > /dev/null
            ;;
            *)
            ;;
        esac
    done
    popd > /dev/null
done

junit_out=junit_report.xml

JAVA_OPTS="-Dtest.build.data=$DIR/build/test/data -Dtest.build.classes=$PWD/test-classes -Dtest.cache.data=$PWD/test-classes"

java -Xmx1024m $JAVA_OPTS -Dorg.schmant.task.junit4.target=$junit_out "$@"

STATUS_CODE=$?

cat $junit_out

if [[ $STATUS_CODE != 0 ]]; then
    echo "FAILURE!"
    exit $STATUS_CODE;
fi

